app = "page-doctor"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "get"
  path = "/health"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 