services:
  - type: web
    name: page-doctor-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV  
        value: production
    healthCheckPath: /health 