// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhugjplvhmtylsnlutts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodWdqcGx2aG10eWxzbmx1dHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODU0NDUsImV4cCI6MjA2OTM2MTQ0NX0.sgQ__Kqk-wTac4fvjwq_ktUio5mGSxKa9kwCUzo9ejo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});